### ISSUE TITLE
Dana Can Cook

### ISSUE THREAD

**Issue by SpearAndFang** [Craluminum-Mods/CraluminumMods-Issues#48]
**Game Version:** Latest
**Mod Version:** Latest

**Description:**
Was trying to place my pumpkin slice sandwich on the ground.  Or maybe eat it according to the crash log

**How to reproduce:**
1. See description. I was probably sneak (crouch) clicking at the time of the crash

**Expected behavior:**
Not crash

**Screenshots / Videos:**

**Log:**
```
Running on 64 bit Windows 10.0.22631.0 with 32565 MB RAM
Game Version: v1.19.8 (Stable)
2024-09-12 7:05:53 AM: Critical error occurred in the following mod: danacancook@0.0.1
Loaded Mods: buzzwords@1.7.0, millwright@1.1.7, primitivesurvival@3.6.5, sortablestorage@2.2.6, thunderlord@1.0.1, translocatorengineeringredux@1.5.1, volumetricshadingreupdated@0.7.5, game@1.19.8, zoombuttonreborn@1.9.0, carryon@1.7.4, danacancook@0.0.1, displaycasewall@1.0.3, hudclock@3.4.0, natsachievements@1.1.0, stepup@1.2.0, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, wildfarmingrevival@1.2.5, configlib@1.3.13
System.NullReferenceException: Object reference not set to an instance of an object.
   at DanaCanCook.SandwichProperties.FromStack(ItemStack stack, IWorldAccessor world) in C:\Users\dana_\Source\Repos\DanaCanCook\DanaCanCook\src\Utility\SandwichProperties.cs:line 61
   at DanaCanCook.ItemSandwich.tryEatBegin(ItemSlot slot, EntityAgent byEntity, EnumHandHandling& handling, String eatSound, Int32 eatSoundRepeats) in C:\Users\dana_\Source\Repos\DanaCanCook\DanaCanCook\src\Item\ItemSandwich.cs:line 279
   at Vintagestory.API.Common.CollectibleObject.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1289
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 831
```

**Comment by Craluminum2413** [comment]
Will be fixed in next update
