### ISSUE TITLE
Banners  0.33.1

### ISSUE THREAD

**Issue by DejFidOFF** [Craluminum-Mods/CraluminumMods-Issues#54]
**Game Version:** 1.20pre6
**Mod Version:** 0.33.1

**Description:**
Every interacting with boaut in game cause the cras

**How to reproduce:**
install mod, take boat from crative inventrory.

```
Running on 64 bit Windows 10.0.22631.0 with 65458 MB RAM
Game Version: v1.20.0-pre.6 (Unstable)
16.10.2024 13:53:10: Critical error occurred in the following mod: flags@0.33.1
Loaded Mods: game@1.20.0-pre.6, flags@0.33.1, creative@1.20.0-pre.6, survival@1.20.0-pre.6
System.MissingMethodException: Method not found: 'Void Vintagestory.GameContent.EntityShapeRenderer.MarkShapeModified()'.
   at Flags.EntityBehaviorBoatWithBanner.OnEvent(String eventName, EnumHandling& handling, IAttribute data)
   at Vintagestory.Client.NoObf.ClientEventAPI.PushEvent(String eventName, IAttribute data) in VintagestoryLib\Client\API\ClientEventAPI.cs:line 484
   at Vintagestory.Common.InventoryPlayerMouseCursor.OnItemSlotModified(ItemSlot slot) in VintagestoryLib\Common\GameContent\Inventory\InventoryPlayerMouseCursor.cs:line 60
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 484
   at Vintagestory.API.Common.ItemSlot.OnItemSlotModified(ItemStack sinkStack) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 425
   at Vintagestory.API.Common.ItemSlotCreative.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op) in VintagestoryApi\Common\Inventory\ItemSlotCreative.cs:line 55
   at Vintagestory.API.Common.ItemSlotCreative.ActivateSlotLeftClick(ItemSlot sinkSlot, ItemStackMoveOperation& op) in VintagestoryApi\Common\Inventory\ItemSlotCreative.cs:line 92
   at Vintagestory.API.Common.ItemSlot.ActivateSlot(ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 290
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 453
   at Vintagestory.Common.InventoryPlayerCreative.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryLib\Common\GameContent\Inventory\InventoryPlayerCreative.cs:line 95
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 973
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 771
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDown(ICoreClientAPI api, MouseEvent mouse) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 739
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) in VintagestoryApi\Client\UI\GuiComposer.cs:line 469
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 549
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 393
   at Vintagestory.Client.NoObf.ClientMain.UpdateMouseButtonState(EnumMouseButton button, Boolean down) in VintagestoryLib\Client\ClientMain.cs:line 1900
   at Vintagestory.Client.SystemHotkeys.OnPrimaryMouseButton(KeyCombination mb) in VintagestoryLib\Client\Systems\Player\Hotkeys.cs:line 50
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack, Boolean keyup) in VintagestoryLib\Client\HotkeyManager.cs:line 422
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean keyUp) in VintagestoryLib\Client\HotkeyManager.cs:line 392
   at Vintagestory.Client.HotkeyManager.OnMouseButton(ClientMain game, EnumMouseButton button, Int32 modifiers, Boolean buttonDown) in VintagestoryLib\Client\HotkeyManager.cs:line 574
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDownRaw(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1875
   at Vintagestory.Client.GuiScreenRunningGame.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 337
   at Vintagestory.Client.ScreenManager.OnMouseDown(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 906
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 201
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseDown(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 12.10.2024 20:43:44, Site = , Source = Application Error, Message = Název chybující aplikace: VintageStory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0x8694
Čas spuštění chybující aplikace: 0x0x1db1cd677d98f8c
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20\VintageStory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20\Lib\openal32.dll
ID zprávy: 2bcc8ce2-4d0b-40d1-a894-bbddaa5b9479
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
```

**Comment by Craluminum2413** [comment]
It will be rewrriten
