### ISSUE TITLE
Mobs Radar

### ISSUE THREAD

**Issue by DerFlammenwerfer** [Craluminum-Mods/CraluminumMods-Issues#57]
**Game Version:** v1.20.0-pre.9 (Unstable)
**Mod Version:** 2.1.1

**Description:**
The game crashes upon attempting to load into a singleplayer game or multiplayer game

**How to reproduce:**
Attempt to join a singleplayer or multiplayer game on this version with the mod installed and loaded.

**Expected behavior:**
The game should load normally -- Please note that it still worked fine on version 1.20.0-pre.5 (Unstable)

**Screenshots / Videos:**
Attach a screenshot / video if it helps explain the issue / shows a visual bug.

**Log:**
```
Running on 64 bit Windows 10.0.22631.0 with 16257 MB RAM
Game Version: v1.20.0-pre.9 (Unstable)
10/31/2024 3:40:51 PM: Critical error occurred in the following mod: mobsradar@2.1.1
Loaded Mods: combatoverhaul@0.0.42, HoneyPress@1.1.2, millwright@1.1.7, nailsmold@1.0.2, nightlight@1.3.6, game@1.20.0-pre.9, blocksoverlay@3.3.0, carryon@1.8.0-pre.1, commonlib@2.5.0-rc.2, fromgoldencombs@1.6.3, maltiezfirearms@0.7.1, mobsradar@2.1.1, creative@1.20.0-pre.9, vsimgui@1.1.6, survival@1.20.0-pre.9, configlib@1.3.16
System.NullReferenceException: Object reference not set to an instance of an object.
   at MobsRadar.MobsRadarMapLayer.OnTick(Single dt) in D:\VSCode\Repos\Modding_VintageStory\MobsRadar\src\MapLayer\MobsRadarMapLayer.cs:line 123
   at Vintagestory.GameContent.WorldMapManager.OnClientTick(Single dt) in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 173
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 19
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 81
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 848
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 740
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 170
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 10/31/2024 3:26:37 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x1308
Faulting application start time: 0x0x1db2bca8ca4f365
Faulting application path: C:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\Games\Vintagestory\Lib\openal32.dll
Report Id: f3a3f8c8-d2d9-42c4-8535-9f597b29d52a
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by Craluminum2413** [comment]
Fixed
